# Manually triggered when a new country is on-boarded
# Add a new country to the variable group, and run the pipeline

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: configdemo-vg

jobs:
  - job: onboard
    displayName: Onboard countries from VG
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Run pipeline'
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: ./onboard-scripts.sh
      env:
        BUILD_NUMBER: $(Build.BuildNumber)
        KEYVAULT_NAME: $(KEYVAULT)
        COUNTRIES: $(COUNTRIES)
        ACCESS_TOKEN_SECRET: $(GITHUB_ACCESS_TOKEN_SECRET)
