trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: configdemo-vg

jobs:
  - job: onboard
    displayName: Onboard countries from VG
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Run pipeline'
      inputs:
        azureSubscription: "Unicef Dev Service Principal"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: ./onboard-scripts.sh
      env:
        KEYVAULT_NAME: $(KEYVAULT)
        COUNTRIES: $(COUNTRIES)