# Development pipeline that runs when changes to helm charts are made

trigger:
 - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Running tests...."
      echo "Tests passed"
    displayName: 'Run tests'
  - script: |
      echo "Running cleanup..."
      echo "Cleanup finished"
    displayName: 'cleanup PR resources'
