apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      helm.fluxcd.io/antecedent: india-sand:helmrelease/india-sand
    creationTimestamp: "2020-05-07T02:01:19Z"
    generation: 2
    labels:
      app: helloworld
    name: helloworld
    namespace: india-sand
    resourceVersion: "341980"
    selfLink: /apis/extensions/v1beta1/namespaces/india-sand/deployments/helloworld
    uid: 4d828d00-7041-4036-bc82-411e3326fdb0
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: helloworld
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: helloworld
      spec:
        containers:
        - env:
          - name: COUNTRY
            value: india
          - name: SECRET
            valueFrom:
              secretKeyRef:
                key: SECRET
                name: envsecret
          image: mperel/helloworld:latest
          imagePullPolicy: Always
          name: helloworld
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-05-07T02:01:24Z"
      lastUpdateTime: "2020-05-07T02:01:24Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-05-07T02:01:19Z"
      lastUpdateTime: "2020-05-07T02:01:24Z"
      message: ReplicaSet "helloworld-865874dd8c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
