apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync 
spec:
  vault:
    name: cerotest-primero-kv # name of key vault
    object:
      name: "github-pat" # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: github-pat # kubernetes secret name
      dataKey: SECRET # key to store object value in kubernetes secret
