{{ if .Values.RUN_JOB  }}
apiVersion: v1
data:
  script.sh: |-
    echo "RUNNING TEST"
    echo "TEST Passed"
    echo "{{ .Values.COUNTRY }}-prod"
    git clone https://github.com/michaelperel/config.git
    cd config
    git checkout -B "{{ .Values.COUNTRY }}-prod"
    git merge master

    repo_url=$(git config --get remote.origin.url)
    repo_url="${repo_url#http://}"
    repo_url="${repo_url#https://}"
    echo "GIT PUSH: https://<ACCESS_TOKEN_SECRET>@$repo_url"
    git push "https://$GIT_PAT@$repo_url"
    echo "GIT PUSH TO PROD SUCCEEDED"
kind: ConfigMap
metadata:
  name: script-configmap
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: script-job
  name: script-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  containers:
    - command:
        - sh
        - /opt/script/script.sh
      image: 'alpine/git'
      name: script
      env:
      - name: GIT_PAT
        valueFrom:
          secretKeyRef:
            name: github-pat
            key: SECRET
      volumeMounts:
        - mountPath: /opt/script
          name: script-configmap
          readOnly: false
  restartPolicy: Never
  volumes:
    - configMap:
        name: script-configmap
      name: script-configmap
{{ end }}
