apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ghana
  namespace: ghana
spec:
  releaseName: ghana
  chart:
    git: git@github.com:michaelperel/config
    path: charts/helloworld
    ref: master
