apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: "italy"
  namespace: "italy"
spec:
  releaseName: "italy"
  chart:
    git: git@github.com:michaelperel/config
    path: charts/helloworld
    ref: master
  values:
    COUNTRY: "italy"
