apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: "japan"
  namespace: "japan"
spec:
  releaseName: "japan"
  chart:
    git: git@github.com:michaelperel/config
    path: charts/helloworld
    ref: master
  values:
    COUNTRY: "japan"
