apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: prod
spec:
  releaseName: helloworld
  chart:
    git: git@github.com:michaelperel/config
    path: charts/helloworld
    ref: master
