apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: "canada-sand"
  namespace: "canada-sand"
spec:
  releaseName: "canada-sand"
  chart:
    git: git@github.com:michaelperel/config
    path: charts/helloworld
    ref: master
  values:
    COUNTRY: "canada"
    RUN_JOB: True
