apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: "sweden-sand"
  namespace: "sweden-sand"
spec:
  releaseName: "sweden-sand"
  forceUpgrade: true
  rollback:
    enable: true
    force: true
    disableHooks: true
  chart:
    git: git@github.com:michaelperel/config
    path: charts/helloworld
    ref: master
  values:
    COUNTRY: "sweden"
    RUN_JOB: True
